version: '2'

services:
  api:
    command: ["npm", "run", "start:dev"]
    ports:
      - ${BACK_PORT}:3000
    build:
      context: ./api/
    container_name: fauna_api
    depends_on:
      - store
    volumes:
      - ./api/src:/fauna/src
    environment:
      APP_VERSION_NUMBER:
      APP_VERSION_LABEL:
      PG_CONNECTION_STRING: postgres://admin:admin@store:5432/fauna
      DOMAIN:

  front:
    build:
      context: ./front/
    container_name: fauna_front
    depends_on:
      - api
    environment:
      REACT_APP_VERSION_NUMBER: ${APP_VERSION_NUMBER}
      REACT_APP_VERSION_LABEL: ${APP_VERSION_LABEL}
      REACT_APP_API_URL:
    volumes:
      - ./front/public:/fauna/public
      - ./front/src:/fauna/src
    ports:
      - ${FRONT_PORT}:3000
    environment:
      REACT_APP_API_URL: "http://${REACT_APP_API_URL}:${BACK_PORT}/"

  store:
    image: postgres
    build:
      context: ./store
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DATABASE: FAUNA
    ports:
      - ${STORE_PORT}:5432