version: '2'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: "${IP_GROUP}"
  system_traefik:
    external: true

services:
  front:
    command: ["npm", "run", "build"]
    volumes:
      - "./front/build:/fauna/build"
  api:
    expose:
      - 3000
    labels:
      traefik.frontend.rule: "Host:${DOMAIN}"
      traefik.port: "3000"
      traefik.docker.network: "system_traefik"
    volumes:
      - "./front/build:/fauna/public"
    networks:
      - default
      - system_traefik
