'use strict';

export const ENCOUNTER_PART_FETCH_LIST = 'ENCOUNTER_PART_FETCH_LIST';
export const ENCOUNTER_PART_FETCH_LIST_SUCCESS = 'ENCOUNTER_PART_FETCH_LIST_SUCCESS';
export const ENCOUNTER_PART_FETCH_LIST_FAILED = 'ENCOUNTER_PART_FETCH_LIST_FAILED';

export const ENCOUNTER_PART_FETCH_ITEM = 'ENCOUNTER_PART_FETCH_ITEM';
export const ENCOUNTER_PART_FETCH_ITEM_SUCCESS = 'ENCOUNTER_PART_FETCH_ITEM_SUCCESS';
export const ENCOUNTER_PART_FETCH_ITEM_FAILED = 'ENCOUNTER_PART_FETCH_ITEM_FAILED';

export const ENCOUNTER_PART_CREATE_ITEM = 'ENCOUNTER_PART_CREATE_ITEM';
export const ENCOUNTER_PART_CREATE_ITEM_SUCCESS = 'ENCOUNTER_PART_CREATE_ITEM_SUCCESS';
export const ENCOUNTER_PART_CREATE_ITEM_FAILED = 'ENCOUNTER_PART_CREATE_ITEM_FAILED';

export const ENCOUNTER_PART_SELECT_ACTIVE = 'ENCOUNTER_PART_SELECT_ACTIVE';
export const ENCOUNTER_PART_SELECT_ACTIVE_SUCCESS = 'ENCOUNTER_PART_SELECT_ACTIVE_SUCCESS';
export const ENCOUNTER_PART_SELECT_ACTIVE_FAILED = 'ENCOUNTER_PART_SELECT_ACTIVE_FAILED';

export const ENCOUNTER_PART_GET_NODE_TREE = 'ENCOUNTER_PART_GET_NODE_TREE';
export const ENCOUNTER_PART_GET_NODE_TREE_SUCCESS = 'ENCOUNTER_PART_GET_NODE_TREE_SUCCESS';
export const ENCOUNTER_PART_GET_NODE_TREE_FAILED = 'ENCOUNTER_PART_GET_NODE_TREE_FAILED';


export const ENCOUNTER_PART_UPDATE_ITEM = 'ENCOUNTER_PART_UPDATE_ITEM';
export const ENCOUNTER_PART_UPDATE_ITEM_SUCCESS = 'ENCOUNTER_PART_UPDATE_ITEM_SUCCESS';
export const ENCOUNTER_PART_UPDATE_ITEM_FAILED = 'ENCOUNTER_PART_UPDATE_ITEM_FAILED';

export const ENCOUNTER_PART_INIT_UPDATE = 'ENCOUNTER_PART_INIT_UPDATE';
export const ENCOUNTER_PART_INIT_UPDATE_SUCCESS = 'ENCOUNTER_PART_INIT_UPDATE_SUCCESS';
export const ENCOUNTER_PART_INIT_UPDATE_FAILED = 'ENCOUNTER_PART_INIT_UPDATE_FAILED';


export function EncounterPartFetchList(id) {
  return {
    type: ENCOUNTER_PART_FETCH_LIST,
    id
  }
}
export function EncounterPartCreateItem(data) {
  return {
    type: ENCOUNTER_PART_CREATE_ITEM,
    data
  }
}

export function EncounterPartSelectActive(id, data) {
	return {
    type: ENCOUNTER_PART_SELECT_ACTIVE,
    id,
		data
	}
}

export function EncounterPartGetNodeTree(id) {
  return {
    type: ENCOUNTER_PART_GET_NODE_TREE,
    id
  }
}

export function EncounterPartUpdateItem(data) {
  return {
    type: ENCOUNTER_PART_UPDATE_ITEM,
    data
  }
}

export function EncounterPartInitUpdate(id) {
  return {
    type: ENCOUNTER_PART_INIT_UPDATE,
    id
  }
}