'use strict';

export const ENCOUNTER_PART_FETCH_LIST = 'ENCOUNTER_PART_FETCH_LIST';
export const ENCOUNTER_PART_FETCH_LIST_SUCCESS = 'ENCOUNTER_PART_FETCH_LIST_SUCCESS';
export const ENCOUNTER_PART_FETCH_LIST_FAILED = 'ENCOUNTER_PART_FETCH_LIST_FAILED';

export const ENCOUNTER_PART_FETCH_ITEM = 'ENCOUNTER_PART_FETCH_ITEM';
export const ENCOUNTER_PART_FETCH_ITEM_SUCCESS = 'ENCOUNTER_PART_FETCH_ITEM_SUCCESS';
export const ENCOUNTER_PART_FETCH_ITEM_FAILED = 'ENCOUNTER_PART_FETCH_ITEM_FAILED';

export const ENCOUNTER_PART_CREATE_ITEM = 'ENCOUNTER_PART_CREATE_ITEM';
export const ENCOUNTER_PART_CREATE_ITEM_SUCCESS = 'ENCOUNTER_PART_CREATE_ITEM_SUCCESS';
export const ENCOUNTER_PART_CREATE_ITEM_FAILED = 'ENCOUNTER_PART_CREATE_ITEM_FAILED';

export const ENCOUNTER_PART_SELECT_ACTIVE = 'ENCOUNTER_PART_SELECT_ACTIVE';


export function EncounterPartFetchList(data) {
  return {
    type: ENCOUNTER_PART_FETCH_LIST,
    data
  }
}
export function EncounterPartCreateItem(data) {
	console.log( data)
  return {
    type: ENCOUNTER_PART_CREATE_ITEM,
    data
  }
}

export function EncounterPartSelectActive(id) {
	return {
		type: ENCOUNTER_PART_SELECT_ACTIVE,
		id
	}
}